go.mod
go.sum

Use BindPlane OP v1.30.0

---

go.mod
go.sum

feat: Update bindplane to 1.33.1

---

go.mod
go.sum

dep(bindplane): Update to bindplane 1.34

---

.github/workflows/ci.yml

Test against 1.31.1

---

go.mod
go.sum

Resolves [CVE-2023-45286](https://nvd.nist.gov/vuln/detail/CVE-2023-45286)

deps(restry): Update to v2.11.0

---

go.mod
go.sum

deps(bindplane): Upgrade to bindplane 1.44.0

---

.github/workflows/ci.yml
example/destination_dynatrace.tf
example/destination_grafana.tf
example/destination_jaeger.tf
example/source_journald.tf

Some examples were out of date. This PR fixes them and adds tests to CI to catch them sooner.

fix: Example resources

---

.github/workflows/ci.yml
Makefile
client/integration_test.go
example/provider.tf
test/integration/docker-compose.yml
test/integration/test.sh

fix(ci): Use bindplane license

---

.github/workflows/ci.yml

chore(ci): Add debug output to test-local

---

.github/workflows/ci.yml

Test more versions and continue on failure

---

go.mod
go.sum
internal/tools/go.mod

deps: 06/12/2024

---

provider/provider.go

When using system auth, auth.type should be set. As of BindPlane v1.59.0, this will be a hard requirement.

fix(config): Set auth.type when using basic auth

---

.github/workflows/ci.yml

Tests against v1.60.0, using client v1.58.0. Waiting for Client v1.61.0 before upgrading, as it should contain some auth fixes.

chore(deps): BindPlane v1.60.0

---

.github/workflows/ci.yml

Updates tests to target BindPlane server v1.61.1

Bindplane 1.61.1

---

.github/workflows/ci.yml

Test against 1.62.0

---

provider/resource_configuration_generic.go

The provider validates the platform before making a request to bindplane. This resolves the following error:
```
│ Error: kubernetes-gateway is not a valid platform
│ 
│   with bindplane_configuration.k8s-gateway,
│   on configuration.tf line 75, in resource "bindplane_configuration" "k8s-gateway":
│   75:   platform = "kubernetes-gateway"
```
```tf
resource "bindplane_configuration" "k8s-gateway" {
lifecycle {
create_before_destroy = true
}
rollout  = true
name     = "k8s-gateway"
platform = "kubernetes-gateway"
source {
name = bindplane_source.k8s_gateway.name
processors = [
bindplane_processor.k8s_include_namespace_default.name,
bindplane_processor.k8s_gateway_log_filter.name,
bindplane_processor.k8s_trace_cleanup.name,
bindplane_processor.k8s_metric_cleanup.name, …
```

fix: Support kubernetes-gateway platform

---

.github/workflows/ci.yml

Test against bindplane 1.63.1

---

go.mod
go.sum

deps(docker): Update docker sdk to v26.1.5

---

SECURITY.md

Enable vulnerability reporting

---

.github/workflows/ci.yml

test against v1.71.0

---

.github/workflows/ci.yml

test against bindplane 1.72

---

.github/workflows/ci.yml

test against v1.73.0

---

.github/workflows/ci.yml

test against v1.74.0

---

.github/workflows/ci.yml

test against v1.75.0

---

.github/workflows/ci.yml

test against v1.76.0

---

.github/workflows/ci.yml

test against v1.81.0

---

.github/workflows/ci.yml

test against v1.82.0

---

.github/workflows/ci.yml

test against v1.83.0

---

.github/workflows/ci.yml
docs/resources/bindplane_configuration_v2.md
docs/resources/bindplane_connector.md

chore: Test against v1.74.0 - current

---

docs/resources/bindplane_configuration_v2.md

chore(doc): Config v2 processor groups

---

internal/component/route.go
internal/configuration/configuration.go
internal/resource/resource.go
provider/resource_configuration_v2.go
test/integration/main.tf
test/local/main.tf

This is mostly working. Connectors can be added to the configuration, however, it is not very usable in its current form. e.g. the Routing connector routes do not work. A follow up PR will address this.

feat: Config v2 connectors

---

docs/resources/bindplane_configuration_v2.md

The config v2 example is missing some route_id and telemetry_type fields.

fix(docs): Configuration V2 missing params

---

.github/workflows/ci.yml

chore: enable merge queue for ci jobs

---

.github/workflows/ci.yml

Bindplane v1.89.3

---

.github/workflows/ci.yml

A recent change in Bindplane should resolve this. When we go to update Bindplane with a new release we should be able to test and merge this.

chore: remove todos from CI workflow

---

docs/resources/bindplane_configuration.md

I noticed this when viewing the docs on the hashicorp site.

fix(docs): Configuration resource code block
